"""add full_name to users

Revision ID: 64bc683c990a
Revises: e7865edf33e8
Create Date: 2026-03-13 00:08:30.595537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '64bc683c990a'
down_revision: Union[str, None] = 'e7865edf33e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
