"""patient_level_access_requests

Revision ID: b4cec4915cb4
Revises: 64bc683c990a
Create Date: 2026-05-13 05:16:05.448125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b4cec4915cb4'
down_revision: Union[str, None] = '64bc683c990a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('affiliation_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('medical_center_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='affiliation_status'), nullable=False),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medical_center_id'], ['medical_centers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Clear existing access_requests — schema is fundamentally changing (per-report → per-patient)
    op.execute('DELETE FROM access_requests')
    op.drop_constraint('access_requests_report_id_fkey', 'access_requests', type_='foreignkey')
    op.drop_column('access_requests', 'report_id')
    op.add_column('access_requests', sa.Column('patient_id', sa.UUID(), nullable=False))
    op.create_foreign_key('access_requests_patient_id_fkey', 'access_requests', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_doctor_patient_access', 'access_requests', ['doctor_id', 'patient_id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_requests', sa.Column('report_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'access_requests', type_='foreignkey')
    op.create_foreign_key(op.f('access_requests_report_id_fkey'), 'access_requests', 'medical_reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_doctor_patient_access', 'access_requests', type_='unique')
    op.drop_column('access_requests', 'patient_id')
    op.drop_table('affiliation_requests')
    # ### end Alembic commands ###
